controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


chrome_devtools_json:
  path: /.well-known/appspecific/com.chrome.devtools.json
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: /
    permanent: false