parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Automatically register all services in the src/ directory
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Cette déclaration n'est pas nécessaire si autoconfigure: true
    # Cependant, si vous voulez une configuration explicite uniquement pour les commandes :
    App\Command\:
        resource: '../src/Command'
        tags: ['console.command']